---
- name: restart jenkins
  systemd:
    name: jenkins
    state: restarted

- name: restart nginx
  systemd:
    name: nginx
    state: restarted

- name: wait jenkins
  uri:
   url: "http://127.0.0.1:8080/cli/"
   status_code: 200
   force_basic_auth: yes
   user: admin
   password: "{{ jenkins_pass.stdout }}"
  register: result
  until: result.status == 200
  retries: 60
  delay: 1
  when: jenkins_pass.rc == 0